- name: Lint PHP
  # You may pin to the exact commit or the version.
  # uses: Firehed/lint-php-action@4e424397e74b38eae09f1cc32621c2f2a65e537a
  uses: Firehed/lint-php-action@v1
  with:
    # Version of PHP
    php-version: # default is latest
    # Comma-separated list of file extensions to lint
    file-extensions: # optional, default is php
